In [2]:
import pandas as pd

frame = pd.read_csv("Q:\\3_Projects\\NVI\\2025\\Final 2025 NVI Dataset 12.16.25v2.csv")

C:\Users\mike\AppData\Local\Temp\ipykernel_8344\2799457432.py:3: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  frame = pd.read_csv("Q:\\3_Projects\\NVI\\2025\\Final 2025 NVI Dataset 12.16.25v2.csv")

In [5]:
for col in frame.columns:
    print(col)

Response_ID
Time Started
Date Submitted
Status
Contact ID
Legacy Comments
Comments
Language
Referer
SessionID
User Agent
Tags
IP Address
Longitude
Latitude
Country
City
State/Region
Postal
By selecting this box, I confirm that I am at least 18 years old, that my primary residence is in the City of Detroit, and that I have read and understand the above information.:Confirm_18_Resident_Consent
Detroit_Residence_Address
Detroit_Residence_UnitNumber
Detroit_Residence_City
Detroit_Residence_State
Detroit_Residence_ZipCode
Hear_Of_Survey
NVI Ambassador. Please enter their name here::Hear_Of_Survey
Other:Hear_Of_Survey
Detroit:Residence_Length
Current_Neighborhood:Residence_Length
Neighborhood:Neighborhood_Safety_Perception
Public_Spaces:Neighborhood_Safety_Perception
Physical:Health_Satisfaction
Mental_Health:Health_Satisfaction
SocioEmotional_Support:Health_Satisfaction
QualityLife_Satisfaction
Youth_in_Household_YesNo
Number_Of_Youth_In_Household
Youth_in_Household_Under5
Youth_in_Household_Under5_specneeds
A relative:Youth_in_Household_Childcare
A friend/ neighbor:Youth_in_Household_Childcare
A school-based childcare or preschool:Youth_in_Household_Childcare
A home-based daycare:Youth_in_Household_Childcare
A community-based childcare center or preschool:Youth_in_Household_Childcare
Kindergarten:Youth_in_Household_Childcare
No one else cares for my child:Youth_in_Household_Childcare
Difficulty_Finding_Want:Youth_in_Household_ChildcareExperience
Satisfied:Youth_in_Household_ChildcareExperience
Difficulty_Finding_Need:Youth_in_Household_ChildcareExperience
Difficulty_Keep_Job:Youth_in_Household_ChildcareExperience
Transportation:Youth_in_Household_ChildcareExperience
Neighborhood:Youth_Safety_Perception
Public_Spaces:Youth_Safety_Perception
Child_Quality_Recreation:Agreement_Statements_Access_and_Support
SchoolProgram_Sports_Tutoring_Participation:Youth_In_Household_Last_12_Months_Questions...56
SchoolProgram_Sports_Tutoring_Participation:Youth_In_Household_Last_12_Months_Questions...57
Youth_Enrolled_In_Out_Of_School_Or_Recreational_Programs
Youth_Enrolled_In_More_Than_One_Program
Currently_Employed
Employment_Impacted_Past12Month
Detroit_Business_Ownership
Annual_Household_Income_From_Own_Business
Quality_of_Housing:Neighborhood_Satisfaction
Condition_of_Vacant_Residential_Buildings:Neighborhood_Satisfaction
Condition_of_Vacant_Commercial_Buildings:Neighborhood_Satisfaction
Condition_of_Vacant_Lots:Neighborhood_Satisfaction
Neighborhood_Infrastructure:Neighborhood_Satisfaction
Illegal_Dump:Neighborhood_Environmental_Severity
Air_Pollution:Neighborhood_Environmental_Severity
Lead:Neighborhood_Environmental_Severity
Stray_Dogs:Neighborhood_Environmental_Severity
Flooding:Neighborhood_Environmental_Severity
Water_Quality:Neighborhood_Environmental_Severity
Heat:Neighborhood_Environmental_Severity
Power-Outages:Neighborhood_Environmental_Severity
Brownfields:Neighborhood_Environmental_Severity
K_12_Public_Charter_Schools:Neighborhood_Access_Satisfaction
Parks_Playgrounds_and_Public Spaces:Neighborhood_Access_Satisfaction
Amenities:Neighborhood_Access_Satisfaction
Neighborhood_Amenities_Use_Frequency:Amenities
Leave_City_For_Amenities_Frequency:Amenities
Welcome_To_Business_and_Services_Perception
Medical_Care:Neighborhood_Health_Related_Access
Mental_Health_Services:Neighborhood_Health_Related_Access
Places_to_be_Active:Neighborhood_Health_Related_Access
Fresh_Healthy_Food:Neighborhood_Health_Related_Access
Housing:Agreement_Statements_Detroit_Access
Financial:Agreement_Statements_Detroit_Access
Medical_Care:Agreement_Statements_Detroit_Access
Mental_Health_Services:Agreement_Statements_Detroit_Access
Human_Services:Agreement_Statements_Detroit_Access
Meets_Needs_Now:Current_Housing
Will_Meet_Needs_10_Years:Current_Housing
Needs_Major_Improvements_Livable:Current_Housing
Needs_Major_Improvements_Get_Around:Current_Housing
Need_Affordable_Housing_Stay_Detroit:Current_Housing
Unhoused:Current_Housing
Own_Or_Rent
Other:Own_Or_Rent
Stay_12_Months:Agreement_Statements_Access_and_Support
Support_Residents:Agreement_Statements_Access_and_Support
Support_Community:Agreement_Statements_Access_and_Support
Not_Able_Pay_Rent_Mortgage:Rent_Utilities_Past_12_Months
Electric_Water_Threatened_Shutoff:Rent_Utilities_Past_12_Months
No_Money_For_Food_Past_12Mos
Finance_Prevent_Healthcare:Needs_In_Past_12_Months
Not_Find_Affordable_Housing:Needs_In_Past_12_Months
At_Risk_Losing_Home:Needs_In_Past_12_Months
Savings_Account
Safe_Reliable_Transportation_Access_Frequency
Religious_Practice:Faith_Activity_Importance
Social:Faith_Activity_Importance
Activities:Faith_Activity_Importance
Community_Activities:Faith_Activity_Importance
Resource_Supports:Faith_Activity_Importance
Health:Prevent_Faith_Attendance
Transportation:Prevent_Faith_Attendance
Faith_Location_Detroit_YN
Fam_Incarcerated_YN:Crime_and_COVID_Best_Answer
Victim_Neighborhood_YN:Crime_and_COVID_Best_Answer
Police:Negatively_Impacted_Or_Harmed_By
Courts:Negatively_Impacted_Or_Harmed_By
Bail_System:Negatively_Impacted_Or_Harmed_By
Immigration_System:Negatively_Impacted_Or_Harmed_By
General distrust of law enforcement:Hesitate_Reporting_Crime_Reason
Concern that I won’t be taken seriously, or no action will be taken:Hesitate_Reporting_Crime_Reason
Fear of retaliation:Hesitate_Reporting_Crime_Reason
Risk of consequences from immigration (such as deportation):Hesitate_Reporting_Crime_Reason
Other:Hesitate_Reporting_Crime_Reason...130
I would not hesitate or avoid reporting crime:Hesitate_Reporting_Crime_Reason
Other:Hesitate_Reporting_Crime_Reason...132
Block_Neighborhood_Community_Group_Participation:Activity_Participation_Frequency
Community_Group_Outside_of_Neighborhod_Participation:Activity_Participation_Frequency
BlockClubParticipation_YesNo
BlockClubName
Community development organization(s):Community_Engagement_Process_Participation
City government:Community_Engagement_Process_Participation
I have not participated in a community engagement process:Community_Engagement_Process_Participation
Other (please describe)::Community_Engagement_Process_Participation...140
Other (please describe)::Community_Engagement_Process_Participation...141
Purchased a lot or lots near my home:In_The_Last_12_Months
Cleaned up or improved lot(s) <u>that I own</u>:In_The_Last_12_Months
Cleaned up or improved lot(s) <u>that I do <b>not</b> own</u>:In_The_Last_12_Months
Secured or improved vacant housing:In_The_Last_12_Months
Cleaned up or improved alley ways:In_The_Last_12_Months
Cleaned up or improved park/open spaces:In_The_Last_12_Months
I have not participated in any of these activities:In_The_Last_12_Months
Television:Community_Events:DigitalEquity_Sources_Information
Radio:Community_Events:DigitalEquity_Sources_Information
Newspaper:Community_Events:DigitalEquity_Sources_Information
Social media:Community_Events:DigitalEquity_Sources_Information
Online search:Community_Events:DigitalEquity_Sources_Information
Friends, neighbors, etc.:Community_Events:DigitalEquity_Sources_Information
Television:Local_Politics:DigitalEquity_Sources_Information
Radio:Local_Politics:DigitalEquity_Sources_Information
Newspaper:Local_Politics:DigitalEquity_Sources_Information
Social media:Local_Politics:DigitalEquity_Sources_Information
Online search:Local_Politics:DigitalEquity_Sources_Information
Friends, neighbors, etc.:Local_Politics:DigitalEquity_Sources_Information
Tablet:Access_Device
Cell_phone:Access_Device
Computer:Access_Device
Yes, I can access the internet at home using a mobile data plan (on my cell phone or via hotspot):Internet_At_Home
Yes, I can access the internet at home using my home internet service:Internet_At_Home
Yes, I can access the internet at home but I’m unsure which of these apply:Internet_At_Home
Yes, I can access the internet at home but I need assistance from a friend or family member to do so:Internet_At_Home
No, I cannot access the internet at home:Internet_At_Home
Yes, I am an Affordable Connectivity Program Subscriber (ACP):Programs_Affordable_Internet
Yes, I use Lifeline:Programs_Affordable_Internet
Yes, I use a program through the Department of Veterans Affairs:Programs_Affordable_Internet
Yes, I use a hotspot from the Detroit Public Library:Programs_Affordable_Internet
Yes, my household uses a program to help pay for the internet but I’m not sure what it is called:Programs_Affordable_Internet
No, I do not have any help in paying for the internet:Programs_Affordable_Internet
Other (if you use a program not listed above to offset the cost of the internet please list it here):Programs_Affordable_Internet
Cost of device:Issues_Prevent_Use_Device
Cost of internet:Issues_Prevent_Use_Device
Slow internet connection:Issues_Prevent_Use_Device
Devices that don’t work well:Issues_Prevent_Use_Device
Having to share a device:Issues_Prevent_Use_Device
Physical difficulty using the device (e.g. the screen is too small to read):Issues_Prevent_Use_Device
Lack of confidence in my ability to use the device or how to use the internet:Issues_Prevent_Use_Device
No, none of these issues have prevented me from using the internet or a device:Issues_Prevent_Use_Device
Concerns about my ability to protect personal information online:Concerns_Using_Devices
Concerns about protecting my financial information:Concerns_Using_Devices
Worries about online security or cyber threats:Concerns_Using_Devices
Fear of being hacked or getting a virus:Concerns_Using_Devices
Worries about tracking and surveillance by companies:Concerns_Using_Devices
Worries about tracking and surveillance by the government:Concerns_Using_Devices
Concerns about being able to determine if online content is real:Concerns_Using_Devices
I do not have any of these concerns:Concerns_Using_Devices
Submitting an online job application:Comfortability_Using_Devices_Task
Passing a basic computer skills test:Comfortability_Using_Devices_Task
Printing and scanning documents:Comfortability_Using_Devices_Task
Uploading documents:Comfortability_Using_Devices_Task
Using Microsoft Office, or Google applications (Word, Excel, PowerPoint, Docs, Sheets, or Slides):Comfortability_Using_Devices_Task
Using email applications (Microsoft Outlook, Gmail):Comfortability_Using_Devices_Task
Using video conferencing software (Zoom, Google Meet):Comfortability_Using_Devices_Task
Using communication and collaboration tools (Slack, Teams):Comfortability_Using_Devices_Task
Writing code:Comfortability_Using_Devices_Task
Using software to analyze data:Comfortability_Using_Devices_Task
Using a website builder:Comfortability_Using_Devices_Task
Using photo or video editing software:Comfortability_Using_Devices_Task
I do not feel comfortable doing any of these tasks:Comfortability_Using_Devices_Task
Finding_job:Importance_Using_Internet_For
Managing_finances:Importance_Using_Internet_For
Education:Importance_Using_Internet_For
Socializing:Importance_Using_Internet_For
Household_shopping:Importance_Using_Internet_For
Gathering_information:Importance_Using_Internet_For
Virtual_doctor_appointments:Importance_Using_Internet_For
Entertainment:Importance_Using_Internet_For
Running_business:Importance_Using_Internet_For
Current_events:Importance_Using_Internet_For
Hobbies:Importance_Using_Internet_For
Affordable internet plans:Resources_Improve_Skills_Access
Better internet availability (faster, more reliable):Resources_Improve_Skills_Access
Access to devices:Resources_Improve_Skills_Access
Basic computer skills training:Resources_Improve_Skills_Access
Advanced computer skills training:Resources_Improve_Skills_Access
Technical support via phone:Resources_Improve_Skills_Access
Technical support in person:Resources_Improve_Skills_Access
None, I do not need any assistance because I can afford reliable internet and I am confident in my abilities.:Resources_Improve_Skills_Access
None, I do not need any assistance because I do not want to use the internet:Resources_Improve_Skills_Access
Other:Resources_Improve_Skills_Access...225
Other:Resources_Improve_Skills_Access...226
Tech Hubs:Familiar_Tech_Resources
Hot spot and device loaner programs at the Detroit Public Library:Familiar_Tech_Resources
Detroit at Work locations:Familiar_Tech_Resources
Other (Please specify any resources you are aware of that are not listed above):Familiar_Tech_Resources...230
Other (Please specify any resources you are aware of that are not listed above):Familiar_Tech_Resources...231
Other (Please specify any resources you are aware of that are not listed above):Familiar_Tech_Resources...232
Racial_Equity1
BRFSS_Work_RaceTreatment
BRFSS_Healthcare_RaceTreatment
Gender_Descriptions
Prefer to self-identify::Gender_Descriptions
Age
Household_Annual_Income_Before_Taxes
African American or Black:Race_And_Ethnicities
American Indian or Alaskan Native:Race_And_Ethnicities
Arab American or Middle Eastern:Race_And_Ethnicities
Asian/Native Hawaiian/Pacific Islander:Race_And_Ethnicities
Hispanic/Latino:Race_And_Ethnicities
White:Race_And_Ethnicities
Some other race::Race_And_Ethnicities...246
Prefer not to answer:Race_And_Ethnicities
Some other race::Race_And_Ethnicities...248
Education_Level
SurveyMotivation
AnythingElse_ShortAnswer
Corrected_Mailing_Address
Corrected_Mailing_Address_Zip
NVIzone2025

In [45]:
cols = [col for col in frame.columns if "Faith" in col]
relevant = frame[cols]

vals = (
    relevant
    .columns.to_frame()
    .reset_index(drop=True)[0]
    .str.split(":", expand=True)
    .rename(columns={0: "question", 1: "group"})
    .assign(full_column=relevant.columns)
)

vals.merge(
    pd.concat([
        (
            frame[col]
            .astype(pd.Int64Dtype())
            .value_counts()
            .to_frame()
            .assign(full_column=col)
            .reset_index(names="answer")
            .drop(columns="count")
        ) for col in cols
    ]),
    on="full_column"
) # .to_clipboard(index=False)

,question,group,full_column,answer
0,Religious_Practice,Faith_Activity_Importance,Religious_Practice:Faith_Activity_Importance,5
1,Religious_Practice,Faith_Activity_Importance,Religious_Practice:Faith_Activity_Importance,4
2,Religious_Practice,Faith_Activity_Importance,Religious_Practice:Faith_Activity_Importance,3
3,Religious_Practice,Faith_Activity_Importance,Religious_Practice:Faith_Activity_Importance,1
4,Religious_Practice,Faith_Activity_Importance,Religious_Practice:Faith_Activity_Importance,2
5,Social,Faith_Activity_Importance,Social:Faith_Activity_Importance,5
6,Social,Faith_Activity_Importance,Social:Faith_Activity_Importance,4
7,Social,Faith_Activity_Importance,Social:Faith_Activity_Importance,3
8,Social,Faith_Activity_Importance,Social:Faith_Activity_Importance,2
9,Social,Faith_Activity_Importance,Social:Faith_Activity_Importance,1
10,Activities,Faith_Activity_Importance,Activities:Faith_Activity_Importance,5
11,Activities,Faith_Activity_Importance,Activities:Faith_Activity_Importance,4
12,Activities,Faith_Activity_Importance,Activities:Faith_Activity_Importance,3
13,Activities,Faith_Activity_Importance,Activities:Faith_Activity_Importance,1
14,Activities,Faith_Activity_Importance,Activities:Faith_Activity_Importance,2
15,Community_Activities,Faith_Activity_Importance,Community_Activities:Faith_Activity_Importance,4
16,Community_Activities,Faith_Activity_Importance,Community_Activities:Faith_Activity_Importance,5
17,Community_Activities,Faith_Activity_Importance,Community_Activities:Faith_Activity_Importance,3
18,Community_Activities,Faith_Activity_Importance,Community_Activities:Faith_Activity_Importance,1
19,Community_Activities,Faith_Activity_Importance,Community_Activities:Faith_Activity_Importance,2
20,Resource_Supports,Faith_Activity_Importance,Resource_Supports:Faith_Activity_Importance,5
21,Resource_Supports,Faith_Activity_Importance,Resource_Supports:Faith_Activity_Importance,4
22,Resource_Supports,Faith_Activity_Importance,Resource_Supports:Faith_Activity_Importance,3
23,Resource_Supports,Faith_Activity_Importance,Resource_Supports:Faith_Activity_Importance,1
24,Resource_Supports,Faith_Activity_Importance,Resource_Supports:Faith_Activity_Importance,2
25,Health,Prevent_Faith_Attendance,Health:Prevent_Faith_Attendance,1
26,Health,Prevent_Faith_Attendance,Health:Prevent_Faith_Attendance,3
27,Health,Prevent_Faith_Attendance,Health:Prevent_Faith_Attendance,0
28,Health,Prevent_Faith_Attendance,Health:Prevent_Faith_Attendance,2
29,Health,Prevent_Faith_Attendance,Health:Prevent_Faith_Attendance,4
30,Transportation,Prevent_Faith_Attendance,Transportation:Prevent_Faith_Attendance,1
31,Transportation,Prevent_Faith_Attendance,Transportation:Prevent_Faith_Attendance,0
32,Transportation,Prevent_Faith_Attendance,Transportation:Prevent_Faith_Attendance,3
33,Transportation,Prevent_Faith_Attendance,Transportation:Prevent_Faith_Attendance,2
34,Transportation,Prevent_Faith_Attendance,Transportation:Prevent_Faith_Attendance,4
35,Faith_Location_Detroit_YN,None,Faith_Location_Detroit_YN,1
36,Faith_Location_Detroit_YN,None,Faith_Location_Detroit_YN,0

In [8]:
import pandas as pd
frame = pd.read_spss("Q:\\3_Projects\\NVI\\2025\\spss.sav")

PyreadstatError: File Q:\3_Projects\NVI\2025\spss.sav does not exist!

In [6]:
frame.columns.to_frame()

                 0
Vrid          Vrid
Vdatesub  Vdatesub
Vstatus    Vstatus
Vcid          Vcid
Vcomment  Vcomment
...            ...
var458      var458
var459      var459
var511      var511
var512      var512
var514      var514

[269 rows x 1 columns]

In [9]:
import pyreadstat

survey = pyreadstat.read_sav("Q:\\3_Projects\\NVI\\2025\\spss.sav")

In [14]:
survey[1].column_names_to_labels

{'Vrid': 'Response ID',
 'Vdatesub': 'Date Submitted',
 'Vstatus': 'Status',
 'Vcid': 'Contact ID',
 'Vcomment': 'Comments',
 'Vlanguage': 'Language',
 'Vreferer': 'Referer',
 'Vsessionid': 'SessionID',
 'Vuseragent': 'User Agent',
 'Vip': 'IP Address',
 'Vlong': 'Longitude',
 'Vlat': 'Latitude',
 'VGeoCountry': 'Country',
 'VGeoCity': 'City',
 'VGeoRegion': 'State/Region',
 'Vpostal': 'Postal',
 'var154O398': 'By selecting this box, I confirm that I am at least 18 years old, that my primary residence is in the City of Detroit, and that I have read and understand the above information :Confirm_18_Resident_Consent',
 'var154O514': 'By selecting this box, I confirm that I have read the above information :Confirm_18_Resident_Consent',
 'var516': 'LinkFromJuly',
 'var338': 'Detroit_Residence_Address',
 'var523': 'Detroit_Residence_UnitNumber',
 'var461': 'Detroit_Residence_City',
 'var462': 'Detroit_Residence_State',
 'var339': 'Detroit_Residence_ZipCode',
 'var507': 'Hear_Of_Survey',
 'var507O1283Othr': 'NVI Ambassador  Please enter their name here::Hear_Of_Survey',
 'var507O1278Othr': 'Other:Hear_Of_Survey',
 'var354': 'LinkFrom',
 'var42': 'Detroit:Residence_Length',
 'var43': 'Current_Neighborhood:Residence_Length',
 'var189': 'Neighborhood:Neighborhood_Safety_Perception',
 'var190': 'Public_Spaces:Neighborhood_Safety_Perception',
 'Physical_Health_Satisfaction': 'Physical:Health_Satisfaction',
 'Mental_Health_Satisfaction': 'Mental_Health:Health_Satisfaction',
 'SocioEmotional_Health_Satisfaction': 'SocioEmotional_Support:Health_Satisfaction',
 'var266': 'QualityLife_Satisfaction',
 'var355': 'Youth_in_Household_YesNo',
 'var187': 'Number_Of_Youth_In_Household',
 'var481': 'Youth_in_Household_Under5',
 'var482': 'Youth_in_Household_Under5_specneeds',
 'var484O1205': 'Option 1:Youth_in_Household_Childcare',
 'var484O1206': 'Option 2:Youth_in_Household_Childcare',
 'var484O1207': 'A relative:Youth_in_Household_Childcare',
 'var484O1208': 'A friend/ neighbor:Youth_in_Household_Childcare',
 'var484O1209': 'A school-based childcare or preschool:Youth_in_Household_Childcare',
 'var484O1210': 'A home-based daycare:Youth_in_Household_Childcare',
 'var484O1211': 'A community-based childcare center or preschool:Youth_in_Household_Childcare',
 'var484O1231': 'Kindergarten:Youth_in_Household_Childcare',
 'var484O1212': 'No one else cares for my child:Youth_in_Household_Childcare',
 'Difficulty_Finding_Want': 'Difficulty_Finding_Want:Youth_in_Household_ChildcareExperience',
 'Satisfied': 'Satisfied:Youth_in_Household_ChildcareExperience',
 'Difficulty_Finding_Need': 'Difficulty_Finding_Need:Youth_in_Household_ChildcareExperience',
 'Difficulty_Keep_Job': 'Difficulty_Keep_Job:Youth_in_Household_ChildcareExperience',
 'Transportation': 'Transportation:Youth_in_Household_ChildcareExperience',
 'var152': 'Neighborhood:Youth_Safety_Perception',
 'var153': 'Public_Spaces:Youth_Safety_Perception',
 'var494': 'Child_Quality_Recreation:Agreement_Statements_Access_and_Support',
 'var95': 'SchoolProgram_Sports_Tutoring_Participation:Youth_In_Household_Last_12_Months_Questions',
 'var96': 'SchoolProgram_Sports_Tutoring_Participation:Youth_In_Household_Last_12_Months_Questions',
 'var97': 'Youth_Enrolled_In_Out_Of_School_Or_Recreational_Programs',
 'var98': 'Youth_Enrolled_In_More_Than_One_Program',
 'var38': 'Currently_Employed',
 'var505': 'Employment_Impacted_Past12Month',
 'var33': 'Detroit_Business_Ownership',
 'var34': 'Annual_Household_Income_From_Own_Business',
 'var52': 'Quality_of_Housing:Neighborhood_Satisfaction',
 'var53': 'Condition_of_Vacant_Residential_Buildings:Neighborhood_Satisfaction',
 'var54': 'Condition_of_Vacant_Commercial_Buildings:Neighborhood_Satisfaction',
 'var55': 'Condition_of_Vacant_Lots:Neighborhood_Satisfaction',
 'var147': 'Neighborhood_Infrastructure:Neighborhood_Satisfaction',
 'var246': 'Illegal_Dump:Neighborhood_Environmental_Severity',
 'var247': 'Air_Pollution:Neighborhood_Environmental_Severity',
 'var248': 'Lead:Neighborhood_Environmental_Severity',
 'var249': 'Stray_Dogs:Neighborhood_Environmental_Severity',
 'var250': 'Flooding:Neighborhood_Environmental_Severity',
 'var251': 'Water_Quality:Neighborhood_Environmental_Severity',
 'var252': 'Heat:Neighborhood_Environmental_Severity',
 'var253': 'Power-Outages:Neighborhood_Environmental_Severity',
 'var254': 'Brownfields:Neighborhood_Environmental_Severity',
 'var63': 'K_12_Public_Charter_Schools:Neighborhood_Access_Satisfaction',
 'var64': 'Parks_Playgrounds_and_Public Spaces:Neighborhood_Access_Satisfaction',
 'var66': 'Amenities:Neighborhood_Access_Satisfaction',
 'var149': 'Neighborhood_Amenities_Use_Frequency:Amenities',
 'var150': 'Leave_City_For_Amenities_Frequency:Amenities',
 'var100': 'Welcome_To_Business_and_Services_Perception',
 'var73': 'Medical_Care:Neighborhood_Health_Related_Access',
 'var74': 'Mental_Health_Services:Neighborhood_Health_Related_Access',
 'var75': 'Places_to_be_Active:Neighborhood_Health_Related_Access',
 'var76': 'Fresh_Healthy_Food:Neighborhood_Health_Related_Access',
 'var16': 'Housing:Agreement_Statements_Detroit_Access',
 'var17': 'Financial:Agreement_Statements_Detroit_Access',
 'var18': 'Medical_Care:Agreement_Statements_Detroit_Access',
 'var19': 'Mental_Health_Services:Agreement_Statements_Detroit_Access',
 'var20': 'Human_Services:Agreement_Statements_Detroit_Access',
 'var371': 'Meets_Needs_Now:Current_Housing',
 'var372': 'Will_Meet_Needs_10_Years:Current_Housing',
 'var373': 'Needs_Major_Improvements_Livable:Current_Housing',
 'var374': 'Needs_Major_Improvements_Get_Around:Current_Housing',
 'var375': 'Need_Affordable_Housing_Stay_Detroit:Current_Housing',
 'var376': 'Unhoused:Current_Housing',
 'var384': 'Own_Or_Rent',
 'var384O1003Othr': 'Other:Own_Or_Rent',
 'var105': 'Stay_12_Months:Agreement_Statements_Access_and_Support',
 'var107': 'Support_Residents:Agreement_Statements_Access_and_Support',
 'var108': 'Support_Community:Agreement_Statements_Access_and_Support',
 'var358': 'Not_Able_Pay_Rent_Mortgage:Rent_Utilities_Past_12_Months',
 'var359': 'Electric_Water_Threatened_Shutoff:Rent_Utilities_Past_12_Months',
 'var356': 'No_Money_For_Food_Past_12Mos',
 'var379': 'Finance_Prevent_Healthcare:Needs_In_Past_12_Months',
 'var380': 'Not_Find_Affordable_Housing:Needs_In_Past_12_Months',
 'var381': 'At_Risk_Losing_Home:Needs_In_Past_12_Months',
 'var36': 'Savings_Account',
 'var37': 'Safe_Reliable_Transportation_Access_Frequency',
 'Religious_Practice': 'Religious_Practice:Faith_Activity_Importance',
 'Social': 'Social:Faith_Activity_Importance',
 'Activities': 'Activities:Faith_Activity_Importance',
 'Community_Activities': 'Community_Activities:Faith_Activity_Importance',
 'var518': 'Resource_Supports:Faith_Activity_Importance',
 'var520': 'Health:Prevent_Faith_Attendance',
 'var521': 'Transportation:Prevent_Faith_Attendance',
 'Faith_Location_Detroit_YN': 'Faith_Location_Detroit_YN',
 'var115': 'Fam_Incarcerated_YN:Crime_and_COVID_Best_Answer',
 'var116': 'Victim_Neighborhood_YN:Crime_and_COVID_Best_Answer',
 'var128': 'Police:Negatively_Impacted_Or_Harmed_By',
 'var129': 'Courts:Negatively_Impacted_Or_Harmed_By',
 'var130': 'Bail_System:Negatively_Impacted_Or_Harmed_By',
 'var131': 'Immigration_System:Negatively_Impacted_Or_Harmed_By',
 'var443O1125': 'Yes:Hesitate_Reporting_Crime_Reason',
 'var443O1126': 'No:Hesitate_Reporting_Crime_Reason',
 'var443O1127': "Don't Know:Hesitate_Reporting_Crime_Reason",
 'var443O1119': 'General distrust of law enforcement:Hesitate_Reporting_Crime_Reason',
 'var443O1120': 'Concern that I won’t be taken seriously, or no action will be taken:Hesitate_Reporting_Crime_Reason',
 'var443O1121': 'Fear of retaliation:Hesitate_Reporting_Crime_Reason',
 'var443O1122': 'Risk of consequences from immigration (such as deportation):Hesitate_Reporting_Crime_Reason',
 'var443O1123': 'Other:Hesitate_Reporting_Crime_Reason',
 'var443O1137': 'Other:Hesitate_Reporting_Crime_Reason',
 'var443O1124': 'I would not hesitate or avoid reporting crime:Hesitate_Reporting_Crime_Reason',
 'var443O1137Othr': 'Other:Hesitate_Reporting_Crime_Reason',
 'var9': 'Block_Neighborhood_Community_Group_Participation:Activity_Participation_Frequency',
 'var10': 'Community_Group_Outside_of_Neighborhod_Participation:Activity_Participation_Frequency',
 'var445': 'BlockClubParticipation_YesNo',
 'var446': 'BlockClubName',
 'var11O11': 'Community development organization(s):Community_Engagement_Process_Participation',
 'var11O12': 'City government:Community_Engagement_Process_Participation',
 'var11O408': 'I have not participated in a community engagement process:Community_Engagement_Process_Participation',
 'var11O13': 'Other (please describe)::Community_Engagement_Process_Participation',
 'var11O13Othr': 'Other (please describe)::Community_Engagement_Process_Participation',
 'var12O16': 'Purchased a lot or lots near my home:In_The_Last_12_Months',
 'var12O17': 'Cleaned up or improved lot(s) that I own:In_The_Last_12_Months',
 'var12O18': 'Cleaned up or improved lot(s) that I do not own:In_The_Last_12_Months',
 'var12O19': 'Secured or improved vacant housing:In_The_Last_12_Months',
 'var12O20': 'Cleaned up or improved alley ways:In_The_Last_12_Months',
 'var12O21': 'Cleaned up or improved park/open spaces:In_The_Last_12_Months',
 'var12O409': 'I have not participated in any of these activities:In_The_Last_12_Months',
 'var471O1186': 'Television:Community_Events:DigitalEquity_Sources_Information',
 'var471O1187': 'Radio:Community_Events:DigitalEquity_Sources_Information',
 'var471O1188': 'Newspaper:Community_Events:DigitalEquity_Sources_Information',
 'var471O1189': 'Social media:Community_Events:DigitalEquity_Sources_Information',
 'var471O1190': 'Online search:Community_Events:DigitalEquity_Sources_Information',
 'var471O1191': 'Friends, neighbors, etc :Community_Events:DigitalEquity_Sources_Information',
 'var472O1186': 'Television:Local_Politics:DigitalEquity_Sources_Information',
 'var472O1187': 'Radio:Local_Politics:DigitalEquity_Sources_Information',
 'var472O1188': 'Newspaper:Local_Politics:DigitalEquity_Sources_Information',
 'var472O1189': 'Social media:Local_Politics:DigitalEquity_Sources_Information',
 'var472O1190': 'Online search:Local_Politics:DigitalEquity_Sources_Information',
 'var472O1191': 'Friends, neighbors, etc :Local_Politics:DigitalEquity_Sources_Information',
 'var440': 'Tablet:Access_Device',
 'var441': 'Cell_phone:Access_Device',
 'var442': 'Computer:Access_Device',
 'var404O1033': 'Yes, I can access the internet at home using a mobile data plan (on my cell phone or via hotspot):Internet_At_Home',
 'var404O1034': 'Yes, I can access the internet at home using my home internet service:Internet_At_Home',
 'var404O1035': 'Yes, I can access the internet at home but I’m unsure which of these apply:Internet_At_Home',
 'var404O1036': 'Yes, I can access the internet at home but I need assistance from a friend or family member to do so:Internet_At_Home',
 'var404O1037': 'No, I cannot access the internet at home:Internet_At_Home',
 'var415O1038': 'Yes, I am an Affordable Connectivity Program Subscriber (ACP):Programs_Affordable_Internet',
 'var415O1039': 'Yes, I use Lifeline:Programs_Affordable_Internet',
 'var415O1040': 'Yes, I use a program through the Department of Veterans Affairs:Programs_Affordable_Internet',
 'var415O1041': 'Yes, I use a hotspot from the Detroit Public Library:Programs_Affordable_Internet',
 'var415O1042': 'Yes, my household uses a program to help pay for the internet but I’m not sure what it is called:Programs_Affordable_Internet',
 'var415O1043': 'No, I do not have any help in paying for the internet:Programs_Affordable_Internet',
 'var415O1044': 'Other (if you use a program not listed above to offset the cost of the internet please list it here):Programs_Affordable_Internet',
 'var416O1045': 'Cost of device:Issues_Prevent_Use_Device',
 'var416O1046': 'Cost of internet:Issues_Prevent_Use_Device',
 'var416O1053': 'Slow internet connection:Issues_Prevent_Use_Device',
 'var416O1054': 'Devices that don’t work well:Issues_Prevent_Use_Device',
 'var416O1055': 'Having to share a device:Issues_Prevent_Use_Device',
 'var416O1056': 'Physical difficulty using the device (e g  the screen is too small to read):Issues_Prevent_Use_Device',
 'var416O1057': 'Lack of confidence in my ability to use the device or how to use the internet:Issues_Prevent_Use_Device',
 'var416O1058': 'No, none of these issues have prevented me from using the internet or a device:Issues_Prevent_Use_Device',
 'var417O1059': 'Concerns about my ability to protect personal information online:Concerns_Using_Devices',
 'var417O1060': 'Concerns about protecting my financial information:Concerns_Using_Devices',
 'var417O1067': 'Worries about online security or cyber threats:Concerns_Using_Devices',
 'var417O1068': 'Fear of being hacked or getting a virus:Concerns_Using_Devices',
 'var417O1069': 'Worries about tracking and surveillance by companies:Concerns_Using_Devices',
 'var417O1070': 'Worries about tracking and surveillance by the government:Concerns_Using_Devices',
 'var417O1071': 'Concerns about being able to determine if online content is real:Concerns_Using_Devices',
 'var417O1072': 'I do not have any of these concerns:Concerns_Using_Devices',
 'var418O1073': 'Submitting an online job application:Comfortability_Using_Devices_Task',
 'var418O1074': 'Passing a basic computer skills test:Comfortability_Using_Devices_Task',
 'var418O1086': 'Printing and scanning documents:Comfortability_Using_Devices_Task',
 'var418O1087': 'Uploading documents:Comfortability_Using_Devices_Task',
 'var418O1088': 'Using Microsoft Office, or Google applications (Word, Excel, PowerPoint, Docs, Sheets, or Slides):Comfortability_Using_Devices_Task',
 'var418O1089': 'Using email applications (Microsoft Outlook, Gmail):Comfortability_Using_Devices_Task',
 'var418O1090': 'Using video conferencing software (Zoom, Google Meet):Comfortability_Using_Devices_Task',
 'var418O1091': 'Using communication and collaboration tools (Slack, Teams):Comfortability_Using_Devices_Task',
 'var418O1092': 'Writing code:Comfortability_Using_Devices_Task',
 'var418O1093': 'Using software to analyze data:Comfortability_Using_Devices_Task',
 'var418O1094': 'Using a website builder:Comfortability_Using_Devices_Task',
 'var418O1095': 'Using photo or video editing software:Comfortability_Using_Devices_Task',
 'var418O1096': 'I do not feel comfortable doing any of these tasks:Comfortability_Using_Devices_Task',
 'var420': 'Finding_job:Importance_Using_Internet_For',
 'var421': 'Managing_finances:Importance_Using_Internet_For',
 'var422': 'Education:Importance_Using_Internet_For',
 'var423': 'Socializing:Importance_Using_Internet_For',
 'var424': 'Household_shopping:Importance_Using_Internet_For',
 'var425': 'Gathering_information:Importance_Using_Internet_For',
 'var426': 'Virtual_doctor_appointments:Importance_Using_Internet_For',
 'var427': 'Entertainment:Importance_Using_Internet_For',
 'var428': 'Running_business:Importance_Using_Internet_For',
 'var429': 'Current_events:Importance_Using_Internet_For',
 'var430': 'Hobbies:Importance_Using_Internet_For',
 'var431O1102': 'Affordable internet plans:Resources_Improve_Skills_Access',
 'var431O1103': 'Better internet availability (faster, more reliable):Resources_Improve_Skills_Access',
 'var431O1104': 'Access to devices:Resources_Improve_Skills_Access',
 'var431O1105': 'Basic computer skills training:Resources_Improve_Skills_Access',
 'var431O1106': 'Advanced computer skills training:Resources_Improve_Skills_Access',
 'var431O1107': 'Technical support via phone:Resources_Improve_Skills_Access',
 'var431O1108': 'Technical support in person:Resources_Improve_Skills_Access',
 'var431O1115': 'None, I do not need any assistance because I can afford reliable internet and I am confident in my abilities :Resources_Improve_Skills_Access',
 'var431O1116': 'None, I do not need any assistance because I do not want to use the internet:Resources_Improve_Skills_Access',
 'var431O1138': 'Other:Resources_Improve_Skills_Access',
 'var431O1109': 'Other:Resources_Improve_Skills_Access',
 'var431O1138Othr': 'Other:Resources_Improve_Skills_Access',
 'var432O1110': 'Tech Hubs:Familiar_Tech_Resources',
 'var432O1111': 'Hot spot and device loaner programs at the Detroit Public Library:Familiar_Tech_Resources',
 'var432O1112': 'Detroit at Work locations:Familiar_Tech_Resources',
 'var432O1113': 'Other (Please specify any resources you are aware of that are not listed above):Familiar_Tech_Resources',
 'var432O1139': 'Other (Please specify any resources you are aware of that are not listed above):Familiar_Tech_Resources',
 'var432O1140': 'Other (Please specify any resources you are aware of that are not listed above):Familiar_Tech_Resources',
 'var432O1139Othr': 'Other (Please specify any resources you are aware of that are not listed above):Familiar_Tech_Resources',
 'var432O1140Othr': 'Other (Please specify any resources you are aware of that are not listed above):Familiar_Tech_Resources',
 'var267': 'Racial_Equity1',
 'var382': 'BRFSS_Work_RaceTreatment',
 'var383': 'BRFSS_Healthcare_RaceTreatment',
 'var135': 'Gender_Descriptions',
 'var135O327Othr': 'Prefer to self-identify::Gender_Descriptions',
 'var136': 'Age',
 'var184': 'Household_Annual_Income_Before_Taxes',
 'var183O456': 'African American or Black:Race_And_Ethnicities',
 'var183O457': 'American Indian or Alaskan Native:Race_And_Ethnicities',
 'var183O458': 'Arab American or Middle Eastern:Race_And_Ethnicities',
 'var183O459': 'Asian/Native Hawaiian/Pacific Islander:Race_And_Ethnicities',
 'var183O460': 'Hispanic/Latino:Race_And_Ethnicities',
 'var183O461': 'White:Race_And_Ethnicities',
 'var183O462': 'Some other race::Race_And_Ethnicities',
 'var183O463': 'Prefer not to answer:Race_And_Ethnicities',
 'var183O462Othr': 'Some other race::Race_And_Ethnicities',
 'var35': 'Education_Level',
 'var236': 'SurveyMotivation',
 'var331': 'Time Spent on Survey',
 'var460': 'AnythingElse_ShortAnswer',
 'var329': 'Receive_NVI_Update',
 'var330': 'Receive_NVI_Update_Email',
 'var456': 'GiftCardAddress_MailConfirm',
 'var458': 'Corrected_Mailing_Address',
 'var459': 'Corrected_Mailing_Address_Zip',
 'var511': 'FirstName',
 'var512': 'LastName',
 'var514': 'TelephoneNumber'}